/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import negocio.*;
import persistencia.*;

/**
 *
 * @author iapereira
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() throws SQLException {
        initComponents();
        prato1.setSelected(true);
        prato1.setActionCommand(prato1.getText());
        prato2.setActionCommand(prato2.getText());
        prato3.setActionCommand(prato3.getText());
        prato4.setActionCommand(prato4.getText());
        prato5.setActionCommand(prato5.getText());
        idComanda.setText(logdao.ultimaId());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaPratos = new javax.swing.ButtonGroup();
        descComandaZerada = new javax.swing.JSpinner();
        quantidadeBebidaZerada = new javax.swing.JSpinner();
        logArea = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        prato1 = new javax.swing.JRadioButton();
        prato3 = new javax.swing.JRadioButton();
        prato2 = new javax.swing.JRadioButton();
        prato4 = new javax.swing.JRadioButton();
        prato5 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        prato6 = new javax.swing.JRadioButton();
        prato7 = new javax.swing.JRadioButton();
        prato8 = new javax.swing.JRadioButton();
        prato9 = new javax.swing.JRadioButton();
        prato10 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        salada1 = new javax.swing.JCheckBox();
        salada3 = new javax.swing.JCheckBox();
        salada2 = new javax.swing.JCheckBox();
        salada4 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        listaSobremesa = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        quantidadeBebida1 = new javax.swing.JSpinner();
        quantidadeBebida2 = new javax.swing.JSpinner();
        quantidadeBebida3 = new javax.swing.JSpinner();
        quantidadeBebida4 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        idComanda = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        taxaServico = new javax.swing.JCheckBox();
        descComanda = new javax.swing.JSpinner();
        botaoFechar = new javax.swing.JButton();
        botaoCalcular = new javax.swing.JButton();
        botaoImprimir = new javax.swing.JButton();
        botaoNovaComanda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listaGarcom = new javax.swing.JComboBox();

        descComandaZerada.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.01d));

        quantidadeBebidaZerada.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante Tio Igor");
        setMinimumSize(new java.awt.Dimension(510, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(logArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 480, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        listaPratos.add(prato1);
        prato1.setText("Filé ao Molho Madeira");

        listaPratos.add(prato3);
        prato3.setText("Filé de Salmão");

        listaPratos.add(prato2);
        prato2.setText("Filé Grelhado");

        listaPratos.add(prato4);
        prato4.setText("Bistecas Suínas Defumadas e Grelhadas");

        listaPratos.add(prato5);
        prato5.setText("Peito de Frango Grelhado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prato1)
                    .addComponent(prato3)
                    .addComponent(prato2)
                    .addComponent(prato4)
                    .addComponent(prato5))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prato1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prato2)
                .addGap(3, 3, 3)
                .addComponent(prato3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prato4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prato5)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        jLabel5.setText("Bebidas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 5, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listaPratos.add(prato6);
        prato6.setText("Filé ao Molho Madeira");

        listaPratos.add(prato7);
        prato7.setText("Filé de Salmão");

        listaPratos.add(prato8);
        prato8.setText("Filé Grelhado");

        listaPratos.add(prato9);
        prato9.setText("Bistecas Suínas Defumadas e Grelhadas");

        listaPratos.add(prato10);
        prato10.setText("Peito de Frango Grelhado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prato6)
                    .addComponent(prato7)
                    .addComponent(prato8)
                    .addComponent(prato9)
                    .addComponent(prato10))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prato6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prato8)
                .addGap(3, 3, 3)
                .addComponent(prato7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prato9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prato10)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        salada1.setText("Alface");
        salada1.setAlignmentY(0.2F);

        salada3.setText("Cenoura");

        salada2.setText("Tomate");

        salada4.setText("Cebola");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salada4)
                    .addComponent(salada1)
                    .addComponent(salada2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salada3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salada1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salada2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salada3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salada4)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 80, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel6.setText("Tipo:");

        listaSobremesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sorvete", "Pudim", "Torta", "Sagu" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listaSobremesa, 0, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(listaSobremesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 240, 40));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel8.setText("Suco:");

        jLabel9.setText("Cerveja:");

        jLabel10.setText("Água:");

        quantidadeBebida1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        quantidadeBebida2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        quantidadeBebida3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        quantidadeBebida4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel7.setText("Refrigerante:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantidadeBebida3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantidadeBebida2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantidadeBebida1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(quantidadeBebida4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(quantidadeBebida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(quantidadeBebida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(quantidadeBebida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(quantidadeBebida4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 130, 110));

        jLabel11.setText("Saladas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 5, -1, -1));

        jLabel12.setText("Saladas");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 5, -1, -1));

        jLabel13.setText("Prato Principal");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        jLabel14.setText("Desconto:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 172, -1, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setText("ID da comanda:");
        jLabel16.setEnabled(false);

        idComanda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idComanda.setText("1");
        idComanda.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(idComanda))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 140, 135, 20));

        jLabel15.setText("Sobremesa");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 175, -1, -1));

        taxaServico.setText("Taxa de Serviço (10%)");
        getContentPane().add(taxaServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 200, -1, -1));

        descComanda.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.01d));
        getContentPane().add(descComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 170, 60, -1));

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });
        getContentPane().add(botaoFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 110, -1));

        botaoCalcular.setText("Calcular");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, -1));

        botaoImprimir.setText("Imprimir");
        botaoImprimir.setEnabled(false);
        botaoImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(botaoImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 110, -1));

        botaoNovaComanda.setText("Nova Comanda");
        botaoNovaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovaComandaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoNovaComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 110, -1));

        jLabel1.setText("Garçom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        listaGarcom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "José", "João" }));
        getContentPane().add(listaGarcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        try {                                              
            logArea.setText("");
            boolean tem10Porcento = taxaServico.isSelected();
            ComandaDAO comandadao = new ComandaDAO();
            Prato prato = new Prato();
            Salada salada = new Salada();
            Sobremesa sobremesa = new Sobremesa();
            JCheckBox[] listaSalada = {salada1, salada2, salada3, salada4};
            String[] nomeBebidas = {"Refrigerante","Suco","Cerveja","Água"};
            JSpinner[] quantidadeBebidas = {quantidadeBebida1,quantidadeBebida2,quantidadeBebida3,quantidadeBebida4};
            ArrayList<Bebida> listaBebidas = new ArrayList();
            double desconto = (double) descComanda.getValue();
            
            String t = "";
            ButtonModel b = listaPratos.getSelection();
            t = b.getActionCommand();
            
            prato.setPrecoString(comandadao.pesquisa("prato", t));
            prato.setNome(t);
            this.logArea.append(prato.getNome() +".........................: R$"+ String.format("%.2f",prato.getPreco()) +"\n");
            

            for (int i = 0; i < listaSalada.length; i++) {
                if (listaSalada[i].isSelected()) {
                    salada.adicionarSalada(listaSalada[i].getText());
                    this.logArea.append(listaSalada[i].getText() + ".........................: R$1,00\n");
                }
            }
            
            for (int i = 0; i < quantidadeBebidas.length; i++) {
                if ((Integer) quantidadeBebidas[i].getValue() > 0) {
                    t = nomeBebidas[i];
                    Bebida bebida = new Bebida();
                    bebida.setPrecoString(comandadao.pesquisa("bebida", t));
                    bebida.setNome(nomeBebidas[i]);
                            bebida.setQuantidade((Integer) quantidadeBebidas[i].getValue());
                            listaBebidas.add(bebida);
                            this.logArea.append(bebida.getNome()+ ".........................: R$"+String.format("%.2f",(bebida.getPreco()*bebida.getQuantidade()))+ "\n");
                }
            }

           t = String.valueOf(listaSobremesa.getSelectedItem());
           sobremesa.setPrecoString(comandadao.pesquisa("sobremesa", t));
           sobremesa.setNome(t);
           this.logArea.append(sobremesa.getNome() +".........................: R$"+ String.format("%.2f",sobremesa.getPreco()) +"\n");
           
           Comanda comanda = new Comanda(Integer.parseInt(idComanda.getText()),
                   listaBebidas, prato, tem10Porcento, sobremesa, salada, desconto, String.valueOf(listaGarcom.getSelectedItem()));
           comanda.setTotal();
           if (tem10Porcento) this.logArea.append("Garçom.........................: R$"+String.format("%.2f",comanda.getGorjeta())+"\n");
           this.logArea.append("Desconto......................: R$"+String.format("%.2f",comanda.getDesconto())+"\n");

           this.logArea.append("\n\nTotal.........................: R$"+String.format("%.2f",comanda.getTotal())+"\n");

            botaoImprimir.setEnabled(true);
            
            listaComanda.add(comanda);
        } catch (SQLException ex) {
             Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_botaoCalcularActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoNovaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovaComandaActionPerformed
        NovaComanda(); 
        botaoImprimir.setEnabled(false);
    }//GEN-LAST:event_botaoNovaComandaActionPerformed

    private void botaoImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImprimirActionPerformed
        try {
            logdao.inserir(listaComanda.get(listaComanda.size()-1));
            idComanda.setText(logdao.ultimaId());
        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        botaoImprimir.setEnabled(false);
        listaComanda.clear();
        NovaComanda();
        
    }//GEN-LAST:event_botaoImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    private ArrayList<Comanda> listaComanda = new ArrayList();
    private LogDAO logdao = new LogDAO();
    
    public boolean NovaComanda(){
        prato1.setSelected(true);
        salada1.setSelected(false);
        salada2.setSelected(false);
        salada3.setSelected(false);
        salada4.setSelected(false);
        listaSobremesa.setSelectedIndex(0);
        quantidadeBebida1.setValue(quantidadeBebidaZerada.getValue());
        quantidadeBebida2.setValue(quantidadeBebidaZerada.getValue());
        quantidadeBebida3.setValue(quantidadeBebidaZerada.getValue());
        quantidadeBebida4.setValue(quantidadeBebidaZerada.getValue());
        descComanda.setValue(descComandaZerada.getValue());
        taxaServico.setSelected(false);
        logArea.setText("");
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoImprimir;
    private javax.swing.JButton botaoNovaComanda;
    private javax.swing.JSpinner descComanda;
    private javax.swing.JSpinner descComandaZerada;
    private javax.swing.JLabel idComanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox listaGarcom;
    private javax.swing.ButtonGroup listaPratos;
    private javax.swing.JComboBox listaSobremesa;
    private java.awt.TextArea logArea;
    private javax.swing.JRadioButton prato1;
    private javax.swing.JRadioButton prato10;
    private javax.swing.JRadioButton prato2;
    private javax.swing.JRadioButton prato3;
    private javax.swing.JRadioButton prato4;
    private javax.swing.JRadioButton prato5;
    private javax.swing.JRadioButton prato6;
    private javax.swing.JRadioButton prato7;
    private javax.swing.JRadioButton prato8;
    private javax.swing.JRadioButton prato9;
    private javax.swing.JSpinner quantidadeBebida1;
    private javax.swing.JSpinner quantidadeBebida2;
    private javax.swing.JSpinner quantidadeBebida3;
    private javax.swing.JSpinner quantidadeBebida4;
    private javax.swing.JSpinner quantidadeBebidaZerada;
    private javax.swing.JCheckBox salada1;
    private javax.swing.JCheckBox salada2;
    private javax.swing.JCheckBox salada3;
    private javax.swing.JCheckBox salada4;
    private javax.swing.JCheckBox taxaServico;
    // End of variables declaration//GEN-END:variables
}
